### PR TITLE
Add git hooks, clean up Makefile, and fix clippy errors

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Comment by mulkieran** [comment]
Also requires some workflow config changes.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Formally requesting the workflow changes here, otherwise it all looks like improvements to me.

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
Looks good. plz squash and I'll merge.

**Comment by jbaublitz** [comment]
@mulkieran Ok, done! Thanks!

**Pull request merged**
