### PR TITLE
Split devicemapper-rs into two crates using workspaces

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Jenkins tests will not pass. They need to be allocated to the separate crates, somehow.

**Comment by mulkieran** [comment]
@agrover @tasleson @trgill review? I don't like the extra complexity of using workspaces compared to just having separate repos and separate crates: see #217, #216. But it should still make for a better experience than keeping the two parts of devicemapper completely undifferentiated.

**Comment by mulkieran** [comment]
rebased.

**Comment by agrover** [comment]
inactive, closing for now.

**Pull request closed without merging**
