### PR TITLE
Test some basic things about thinpool usage

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
@trgill I left some junk on the Jenkins instance.

**Comment by trgill** [comment]
@mulkieran ok - I removed the dm devices.  Do you understand why they didn't get removed?  After the tests complete we run "dmsetup remove_all --force".

**Comment by mulkieran** [comment]
@trgill Alas, no.

**Comment by mulkieran** [comment]
Note:

```
---- thindev::tests::loop_test_snapshot_usage stdout ----
	thread 'thindev::tests::loop_test_snapshot_usage' panicked at 'assertion failed: `(left == right)`
  left: `DataBlocks(8228)`,
 right: `DataBlocks(87)`', src/thindev.rs:630:8
```

The upper one is the number of data blocks required when the thin device is 1 TiB. It's a smidge over 1/2 GiB.

**Comment by mulkieran** [comment]
@agrover @trgill review, please?

**Comment by mulkieran** [comment]
Trying to add one more test to confirm that setting the UUID causes space consumption.

**Comment by mulkieran** [comment]
Confirmed!

**Comment by mulkieran** [comment]
@agrover review, please?

**Comment by agrover** [comment]
👍 , MALR

**Pull request merged**
