### PR TITLE
Fix enospc when testing on system  with small tmpfs

### PR DESCRIPTION
**Pull request by tasleson**
Previously `get_devices` was creating a sparse file by opening the file,
seeking and writing to the end.  Then it was converted to using `fallocate`
which was creating a non-sparse file.  Fallocate can make an existing file
sparse or add to an existing file as sparse, but for simplying creating
a sparse file to start with `ftruncate` is the simplest approach.

Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by tasleson** [comment]
My test VM is getting many errors that look like the following when running master

``` text
---- cachedev::tests::loop_test_cache_size_change stdout ----
	thread 'cachedev::tests::loop_test_cache_size_change' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(ENOSPC)', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
             at /builddir/build/BUILD/rustc-1.26.0-src/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /builddir/build/BUILD/rustc-1.26.0-src/src/libcore/result.rs:782
  10: devicemapper::loopbacked::get_devices
             at src/loopbacked.rs:106
  11: devicemapper::loopbacked::test_with_spec
             at src/loopbacked.rs:134
  12: devicemapper::cachedev::tests::loop_test_cache_size_change
             at src/cachedev.rs:994
  13: devicemapper::__test::TESTS::{{closure}}
             at src/cachedev.rs:993
  14: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.26.0-src/src/libcore/ops/function.rs:223
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: __rust_maybe_catch_panic
```

**Comment by agrover** [comment]
My bad! nix has had `ftruncate` support for a long time it looks like, but I didn't know it was what we should be using. Should've just used it from the beginning.

:+1:

**Comment by mulkieran** [comment]
I'm adding this to the Stratis Project and putting it in review column as I believe it is intended to be reviewed.

**Comment by mulkieran** [comment]
This change should be done in stratisd as well, I should think.

**Comment by agrover** [comment]
thanks!

**Pull request merged**
