### PR TITLE
Remove wait_for_dm calls

### LINKED ISSUE #100: We sleep for a time waitng for DM devices to become available (remove wait_for_dm)
See: https://github.com/stratis-storage/stratisd/issues/260.

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves #100.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
I think our tests will fail...

**Comment by mulkieran** [comment]
Surprise. @agrover @trgill review?

**Comment by mulkieran** [comment]
We should see, also, if the loops in the dm tests can be eliminated.

**Comment by mulkieran** [comment]
They can. woohoo!

**Comment by agrover** [comment]
👍 merging as last reviewer

**Pull request merged**
