### PR TITLE
Make new() and setup() methods approach idempotency

### PR DESCRIPTION
**Pull request by mulkieran**
Do not fail, if when setting up or creating a DM device, it is already registered with the kernel.

### CODE REVIEW

**Comment by mulkieran** [comment]
This is the non-test code from #110. I plan to put together a test PR separately.
However, the code itself should be identical to that in in #110.

**Comment by mulkieran** [comment]
This code is also being tested indirectly in https://github.com/stratis-storage/stratisd/pull/490, which is currently passing. However, the test in that PR is utterly basic, I welcome suggestions for better tests.

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by agrover** [comment]
Looks fine to me 👍

**Comment by mulkieran** [comment]
@trgill review?

**Comment by mulkieran** [comment]
@agrover @trgill I'll try to come up with better testing on the stratisd side. But if this looks good enough, it might be time to cut a new release. Then we can make use of this change and division through the release instead of the git branch.

**Pull request merged**
