### PR TITLE
bump loopdev to 0.2

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Wierd behavior of Travis, restarted build.

**Comment by mulkieran** [comment]
Jenkins, ok to test.

**Comment by mulkieran** [comment]
Jenkins, test this please.

**Comment by mulkieran** [comment]
Jenkins will not obey me today. But, since Travis runs all loopbacked tests anyway, I don't think that's a reason to hold up this PR.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
👍 , merging, thanks!

**Pull request merged**
