### PR TITLE
Fix clippy errors for Rust beta 1.47

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#210

### CODE REVIEW

**Comment by bgurney-rh** [comment]
unfortunately, Rust 1.45 clippy reports: `unknown clippy lint: clippy: same_item_push`

**Comment by bgurney-rh** [comment]
I removed the commit with the `#[allow(clippy::same_item_push)]` in `src/core/dm.rs`, since that doesn't seem to be working with the 1.45 clippy version.

**Comment by mulkieran** [comment]
We decided to merge what we can fix. We will have to keep the beta task as non-mandatory until we complete several more of the Rust 1.46 upgrade steps.

**Comment by mulkieran** [comment]
EBUSY on test, sigh, re-running.

**Pull request merged**
