### PR TITLE
Allow passing feature args in ThinPoolDev::new()

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
The only changes required in stratisd are here: https://github.com/mulkieran/stratisd/commit/84a2cb4089d8d6feb9a84de38b4d25f4382fca7c.

**Comment by mulkieran** [comment]
@jbaublitz I'm proposing that we merge this PR, make a 0.32.0 release, update stratisd's devicemapper dependency, and then release stratisd version 3.0.3, with the devicemapper dependency version bump being about the last change in stratisd 3.0.3. Plz take special note of the commit where I move the suspend action into the if statement.

**Review by jbaublitz — APPROVED** [review]
Okay, this looks good!

**Comment by jbaublitz** [comment]
> The only changes required in stratisd are here: [mulkieran/stratisd@84a2cb4](https://github.com/mulkieran/stratisd/commit/84a2cb4089d8d6feb9a84de38b4d25f4382fca7c).

Just a note that these changes should probably be tweaked. It doesn't make much sense to create a pool with two of the required parameters and then add the third when we can put them all in the `ThinPoolDev::new()` call now after this change. Do you see the part of the code I'm talking about?

**Comment by mulkieran** [comment]
> > The only changes required in stratisd are here: [mulkieran/stratisd@84a2cb4](https://github.com/mulkieran/stratisd/commit/84a2cb4089d8d6feb9a84de38b4d25f4382fca7c).
> 
> Just a note that these changes should probably be tweaked. It doesn't make much sense to create a pool with two of the required parameters and then add the third when we can put them all in the `ThinPoolDev::new()` call now after this change. Do you see the part of the code I'm talking about?

Thanks for noticing! I fixed it here: https://github.com/mulkieran/stratisd/commit/0c1b727bf7b7a82ef8c5a4dd073e99c262a70bac, but the I forgot to update the link.

**Comment by jbaublitz** [comment]
Okay, great! Thanks!

**Pull request merged**
