### PR TITLE
Add optional external_origin_dev to TargetParams

### PR DESCRIPTION
**Pull request by mulkieran**
For completeness sake and in order to eliminate future bugs.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review? This one is almost, but not quite, trivial.

**Comment by mulkieran** [comment]
Cherry-picked from #239.

**Comment by agrover** [comment]
I guess, for completeness... 👍

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@trgill review?

**Pull request merged**
