### PR TITLE
Updates for rustfmt 0.8.3

### PR DESCRIPTION
**Pull request by trgill**
Update the code using rustfmt 0.8.3 as needed
Update the Makefile to include a format check as part of CI
Allow for 110 character line length.  The default is 100.  The code had a pointer to a long
URL.  I think allowing 110 is better than removing the comment.

### CODE REVIEW

**Comment by trgill** [comment]
@agrover @mulkieran review please.  I think mostly trivial changes.

I added a rustfmt.tom to allow 110 chars.  There is a comment is dm.rs that points to this URL:

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/device-mapper

After indentation it ends up to be around 105 chars.

**Comment by mulkieran** [comment]
Better to split the URL and accept the defaults, I would think. I wouldn't like the lines to get any longer.

**Comment by trgill** [comment]
Ok, I removed the rustfmt.toml and split the URL.

**Comment by agrover** [comment]
👍

**Pull request merged**
