### PR TITLE
Improve doc comments generated by macros

### PR DESCRIPTION
**Pull request by waltdisgrace**
I removed the doc comments containing $T.

I began to add my own doc comments, but I do not know how to make the
comments change depending on the $display_name.

How should I go about doing this?

### CODE REVIEW

**Comment by mulkieran** [comment]
What do you see when you run '> make docs'?

**Comment by mulkieran** [comment]
You'll have to intuit how and where the rust doc command picks up ```///``` comments in order to generate docs. Play w/ it slowly and carefully, making one change, and then inspecting the generated docs to see what the effect is.

**Comment by waltdisgrace** [comment]
@mulkerian See this related issue: https://github.com/rust-lang/rust/issues/37903

**Comment by waltdisgrace** [comment]
@mulkieran See this related issue: rust-lang/rust#37903

**Comment by waltdisgrace** [comment]
@mulkieran See related issue: https://github.com/rust-lang/rust/issues/37903

**Comment by mulkieran** [comment]
> @mulkieran See related issue: [rust-lang/rust#37903](https://github.com/rust-lang/rust/issues/37903)

Whoops! Thanks for finding this out.

So we have to back up and set our sites a bit lower.

1. Remove those nonsense comments w/ the $Ts that show up in the docs, because they do just look like garbage.
2. I'll try to rewrite that explanation of the type I sent you so that it's completely generic, and you can figure out how to include that.

But I don't think there's much more that can be done that would make a positive difference, so we might as well stop there.

**Comment by mulkieran** [comment]
Obsoleted, since we want to make a bigger change in the implementation.

**Pull request closed without merging**
