### PR TITLE
Extend real tests, those that require sudo

### PR DESCRIPTION
**Pull request by mulkieran**
This extends the existing DM test and add some related header docs and small code changes.

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by trgill** [comment]
not sure it makes sense to split out the tests by "sudo required".  unless we change the permissions, won't all the tests that open /dev/xxx "read/write"  require sudo?

**Comment by mulkieran** [comment]
Yes, they will. But, we now have five tests that do not require 'sudo', and we should plan to have more.

**Comment by agrover** [comment]
👍 last reviewer, merging.

**Pull request merged**
