### PR TITLE
parse_table_status: add same_item_push clippy allow

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#210

### CODE REVIEW

**Comment by mulkieran** [comment]
This is fine, but even 1.46 doesn't recognize the new lint. We should talk to clippy about ignoring unrecognized lints.

**Comment by mulkieran** [comment]
@bgurney-rh : Try ```clippy::all``` instead of ```clippy::same...```.

**Comment by bgurney-rh** [comment]
OK; I'll modify the allow to `clippy::all`, and add an extra comment.

**Review by mulkieran — APPROVED** [review]

**Review by drckeefe — APPROVED** [review]

**Comment by mulkieran** [comment]
@bgurney-rh: That worked! You can make the beta task mandatory again.

**Review by mulkieran — CHANGES_REQUESTED** [review]
In a separate commit...make the task mandatory again. I guess we should remember the clippy::all trick for next time.

**Review by mulkieran — APPROVED** [review]

**Review by jbaublitz — APPROVED** [review]

**Pull request merged**
