### PR TITLE
Suspend device before loading table

### PR DESCRIPTION
**Pull request by mulkieran**
This is intuitively the correct thing to do.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover review?

**Comment by mulkieran** [comment]
I think that this is an obvious fix to a bug, but I believe that it turns out that we have bigger problems and that those mean that we should not be including suspend and resume calls in ```table_reload``` at all. We need to manage suspend and resume at a higher level. For example, when we set the segments of the data device of a thin pool, it seems that it is necessary to:
1. Suspend the thinpool.
2. Suspend the data device
3. Reload the data device table.
4. Resume the data device.
5. Reload the thin pool device table.
6. Resume the thin pool device.

What we have here is a nested structure, and our current setup breaks that. Do we know if suspending and resuming are idempotent? That would make things easier.

**Comment by agrover** [comment]
So the way this works is that `table_load` does not replace the active table, it loads it into the "inactive" slot, and then whatever is in the inactive slot is moved to the "active" slot when the device is suspended/resumed. Based on the comments in dm-ioctl.h, looking at (table_load, suspend, resume) sequence, table_load loads the new (inactive) table, suspend flushes all pending i/o, and resume makes the inactive table active. Doing the suspend before the table_load seems allowed, but keeps the device suspended marginally longer than doing the table load first. Note that it is possible to resume a non-suspended device to make the inactive table active without flushing i/o. This seems like something one might need to do in some edge case, but unwise for the common case.

Also, suspend and resume are indeed idempotent.

**Comment by mulkieran** [comment]
Thanks for the explanation!

It is good that suspend and resume are idempotent, because that makes things slightly easier for us.

Right now our code for setting the thinpool data segments:
1. Loads a new table for the data device into the inactive slot.
2. Suspends the data device.
3. Resumes the data device.
4. Loads a new table for the thin pool device into the inactive slot.
5. Suspends the thinpool device.
6. Resumes the thinpool device.

But the test code in ```devicem-mapper-test-suite``` follows the order in .

**Comment by agrover** [comment]
Seems best to be consistent, even if both sequences are not "wrong" per se.

**Comment by mulkieran** [comment]
I'm dropping this in favor of issue #253.

**Pull request closed without merging**
