### PR TITLE
bump bitflags to 1.0

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Note that this is BREAKING CHANGE, so you would have to release 0.15.0 as next release.

**Comment by mulkieran** [comment]
This is definitely a change for the better. Please go ahead and fix the rustfmt issues and force push the new version. We are forced to use a particular version of rustfmt (designated in the Makefile), because at the last time we reviewed the subject, all subseqent versions did terrible things to our code.

**Comment by ignatenkobrain** [comment]
@mulkieran done

**Comment by mulkieran** [comment]
Jenkins, test this please.

**Comment by agrover** [comment]
thanks everybody!

**Pull request merged**
