### PR TITLE
Fix autogenerated docs

### PR DESCRIPTION
**Pull request by jbaublitz**
Resolves: #463.

### CODE REVIEW

**Comment by mulkieran** [comment]
Please just get rid of the comment on ```checked_add``` which has a related problem while you're here, so you can make a clean sweep of it.

**Comment by jbaublitz** [comment]
Instead of having to use `#[allow(missing_docs)]`, I modified the docs slightly to be less specific but still somewhat helpful. Does that work?

**Comment by mulkieran** [comment]
> Instead of having to use `#[allow(missing_docs)]`, I modified the docs slightly to be less specific but still somewhat helpful. Does that work?

Aaah, that explains why it was documented in the first place! Yes, that's best.

**Comment by jbaublitz** [comment]
Should I rebase and squash?

**Comment by jbaublitz** [comment]
@mulkieran Good to go.

**Comment by jbaublitz** [comment]
Should I merge?

**Pull request merged**
