### PR TITLE
Integrity WIP

### PR DESCRIPTION
**Pull request by agrover**
Here's some not yet working code to support a dm-integrity target, if somebody wanted to pick this up and get it working.

EDIT: code now works.

### CODE REVIEW

**Comment by agrover** [comment]
Hi please review this and consider merging? Thanks.

**Comment by mulkieran** [comment]
Travis tests did something strange, Jenkins tests are failing.

**Comment by mulkieran** [comment]
Closing as this is not really part of our plan at this time.

**Comment by agrover** [comment]
what is the plan?

**Comment by mulkieran** [comment]
Not sure yet. If you open an issue and link it to this PR, we can track it better.

**Pull request closed without merging**
