### PR TITLE
Change *extend methods to *reset methods

### PR DESCRIPTION
**Pull request by mulkieran**
See stratisd issue https://github.com/stratis-storage/stratisd/issues/550 for motivation.

### CODE REVIEW

**Comment by mulkieran** [comment]
Corresponding stratisd PR: https://github.com/stratis-storage/stratisd/pull/606.

**Comment by agrover** [comment]
looks good except I'm iffy on naming them "reset", which IMO doesn't have quite the right connotations. "reload"? "set_segments"? "reconfigure"? Other ideas?

**Comment by mulkieran** [comment]
ok, ```set_segments``` is fine.

**Comment by mulkieran** [comment]
@agrover Naming changes acceptable?

**Comment by agrover** [comment]
Thanks!!!

**Pull request merged**
