### PR TITLE
Generate UML-diagram like graphs for devicemapper-rs

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Jenkins uses sudo_test, so it doesn't like test-sudo. That's probably an easy change, though.

**Comment by agrover** [comment]
Looks fine, but can we stick uml_graphs.rs in a directory? My first thought was docs/utils or docs/scripts or something...

**Comment by mulkieran** [comment]
How about this? The subdirectory is just "scripts", which kind of makes sense for something that is run using ```cargo script```.

**Comment by mulkieran** [comment]
Might as well consider it ready for final review.

**Pull request merged**
