### PR TITLE
Remove dev dependency on libudev

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/548

### CODE REVIEW

**Comment by mulkieran** [comment]
This can be merged next week.

**Review by jbaublitz — COMMENTED** [review]
I'm a little uncertain about this. I'm wondering if there's something about thin devices or filesystems that we're missing. This may specifically be a test for whether `uevent.is_initialized()` returns `false` or something similar.

**Comment by mulkieran** [comment]
Related bz https://bugzilla.redhat.com/show_bug.cgi?id=1312011

**Comment by mulkieran** [comment]
This doesn't need to go in now. We can take our time and review the related stratisd PR also.

**Pull request merged**
