### PR TITLE
Travis: Use container infrastructure

### PR DESCRIPTION
**Pull request by rnestler**
This removes the `sudo: required` from all builds except the `sudo_test` one, which should improve the CI boot time. See https://docs.travis-ci.com/user/reference/precise/#Virtualization-environments for more information.

### CODE REVIEW

**Comment by rnestler** [comment]
> Why is it "Try ...", why not just "Enable..."?

Ah sorry, I was not sure at first if it will work and forgot to rephrase it during rebase.

**Comment by rnestler** [comment]
>Weirdly, though, the fmt target is taking about 3 minutes longer than previously. @rnestler Do you have any idea why?

No idea why, seems odd :confused: I'll rephrase the commit message and re-trigger a build.

**Comment by rnestler** [comment]
We could try to enable [cargo caching](https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache) to further improve build times.

**Comment by agrover** [comment]
👍

**Comment by mulkieran** [comment]
@agrover I'm trying to understand why cargo cacheing would help in our situation (it doesn't seem to hurt).

**Comment by rnestler** [comment]
>@agrover I'm trying to understand why cargo cacheing would help in our situation (it doesn't seem to hurt, but I think we should understand it).

The cargo cache will cache the download and compilation of all dependencies and the rustfmt binary.

I'll re trigger the build to check if there are any issues if the cache is present (cargo may complain if rustfmt is already installed).

**Comment by rnestler** [comment]
Ah the Makefile doesn't try to install rustfmt if it is already present, so it works fine with caching.

**Comment by mulkieran** [comment]
Ok. It all looks fine to me. @agrover if you're satisfied, feel free to merge.

**Comment by agrover** [comment]
Thanks @rnestler!

**Pull request merged**
