### PR TITLE
Non-semantic changes

### PR DESCRIPTION
**Pull request by mulkieran**
These are mostly additional header comments along with a few minor code adjustments for greater clarity.

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review?

These are changes cherry-picked from #110. They are many of them additional header comments. Please examine the header comments for correctness, if they are wrong, it would be good to know soon.

**Comment by mulkieran** [comment]
Failing due to some clippy errors, see #135. Will rerun in a bit.

**Comment by trgill** [comment]
Since the clippy changes are unrelated to this PR, I gave it the 👍 - LGTM once the errors are resolved.

**Comment by agrover** [comment]
👍 , merging as last reviewer.

**Pull request merged**
