### PR TITLE
Use a TargetTable trait to represent a device's table

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #229.
Resolves: #230.
Resolves: #244.

### CODE REVIEW

**Comment by mulkieran** [comment]
Rebased roughly.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebases and changes.

**Comment by mulkieran** [comment]
@trgill Hi Jenkins test failed, but I can't look at it, and it seems to prevent Travis from running.

**Comment by trgill** [comment]
@mulkieran OpenStack nodes are not responding to Jenkins.  Looks like all? of them... Will track it down.

**Comment by mulkieran** [comment]
@trgill Thanks!

**Comment by mulkieran** [comment]
spurious Jenkins failure.

**Comment by mulkieran** [comment]
Get rid of dead code annotation.

**Comment by mulkieran** [comment]
@agrover This builds on previous reorganization work and makes it possible to have a LinearDev with flakey bits. It has not been completed, looking for any immediate feedback you have.

**Comment by mulkieran** [comment]
Probably the right thing to do is to extend Segment with an optional field for flakey info, a struct that has
```up_interval```, ```down_interval```, and feature args.  If it is not ```None``` then target is flakey. This looks straightforward, I think the only function that would need to be altered is ```LinearDevTargetTable::new```.

**Comment by agrover** [comment]
The LinearDev doesn't know the type of the blockdevs it is mapping. They could be any blockdev, either DM or non-DM. Their params (if any) aren't visible to the LinearDev. `LinearDevTargetParams` seems to be constraining each segment making up a Linear to be either another Linear or a Flakey, which doesn't seem right.

**Comment by mulkieran** [comment]
@agrover I don't think that's true. These targets just constrain how the linear dev views the underlying device, not what the underlying device is. So, a linear target can map over any type of underlying device. A flakey target can do the same.

There is another point, which is that currently each line in a linear dev can only be flakey or linear target, due to the definition of LinearDevTargetParams. I think there is also a delay target, which could be added later without any great difficulty, and just another use of Either constructor.

**Comment by mulkieran** [comment]
There is a tweak that I think will make this a bit cleaner. Have TargetParams include the ```target_type``` value. In that case, parseing and display will include this value, and even LinearDevTargetParams can implement FromStr by reading the first value, which will identify the target type and then dispatching to the appropriate TargetParam implementation, either Flakey or Linear.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
After digging around in the kernel code, the list of DM devs that can only have a single target (.features include DM_TARGET_SINGLETON) is:
* thin-pool
* mpath
* integrity
* zoned

AFAICT *all* the other ones (10+) can be used for devices that have multiple target lines in their table. (Doing so might be silly in some cases, but it's possible).

So yeah, there is no such thing as a FlakeyDev, only a device with a "flakey" target line (among possibly others). No such thing as a LinearDev.

Good to get clear on all this, but this suggests we will need to rework our dm upper layer at some point, to not artificially restrict the possible DM configurations.

**Comment by mulkieran** [comment]
The restriction you've found seems incomplete to me.It's easy for me to understand why a thin-pool target must be the unique one on a DM device, but it is hard for me to understand why that same restriction wouldn't apply for a cache target. Maybe someone just forgot to set ```DM_TARGET_SINGLETON``` for some targets, or didn't want to go to the trouble.

Anyway, this PR does go in  the right direction, by setting up LinearDev so that it can use either type of target, flakey or linear in a way that makes sense. Running together a bunch of cache and thindev targets on a single device does seem a little silly to me. So, it probably won't hurt us to leave all that alone for now.

After all, so long as the upper layer isn't actually wrong, it's probably alright if it reflects our prejudices.

This is one of the many reasons why I think the upper layer should end up in a separate library. I can't imagine we'ld ever have these sorts of discussions about the core part of the library. It's a completely different kettle of fish.

**Comment by agrover** [comment]
>This is one of the many reasons why I think the upper layer should end up in a separate library. I can't imagine we'ld ever have these sorts of discussions about the core part of the library. It's a completely different kettle of fish.

I opened this so we can discuss independently of other ongoing PRs: https://github.com/stratis-storage/devicemapper-rs/issues/220

**Comment by agrover** [comment]
> The restriction you've found seems incomplete to me.It's easy for me to understand why a thin-pool target must be the unique one on a DM device, but it is hard for me to understand why that same restriction wouldn't apply for a cache target. Maybe someone just forgot to set DM_TARGET_SINGLETON for some targets, or didn't want to go to the trouble.

I don't know, maybe we can ask?

**Comment by mulkieran** [comment]
Look at #255 instead.

**Comment by mulkieran** [comment]
Superceded by #255.

**Pull request closed without merging**
