### PR TITLE
Disentangle outer devicemapper layer from core

### PR DESCRIPTION
**Pull request by mulkieran**
Should be a lot tidier.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Jenkins failure is due to a cleanup problem.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Travis build canceled because it was taking forever.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
I am actively rebasing them and I like to get the benefit of the CI.

**Comment by agrover** [comment]
If so, you can enable travis for mulkieran/devicemapper-rs and create a pull request against mulkieran/master, and it should run CI. Can you give this a try?

**Comment by mulkieran** [comment]
https://github.com/mulkieran/devicemapper-rs/pull/1

**Comment by mulkieran** [comment]
No Jenkins, though.

**Pull request closed without merging**
